#pragma once

#include "../SDK.h"

// Name: Astroneer-SDK, Version: 1.0.0

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

namespace SDK
{
//---------------------------------------------------------------------------
// Parameters
//---------------------------------------------------------------------------

// Function ControlPanelPrinter_AnimBP.ControlPanelPrinter_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelPrinter_AnimBP_AnimGraphNode_TransitionResult_6DF852284DB712D933B624913F600534
struct UControlPanelPrinter_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelPrinter_AnimBP_AnimGraphNode_TransitionResult_6DF852284DB712D933B624913F600534_Params
{
};

// Function ControlPanelPrinter_AnimBP.ControlPanelPrinter_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelPrinter_AnimBP_AnimGraphNode_TransitionResult_55CADA634E04C07CACFD52B557498337
struct UControlPanelPrinter_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelPrinter_AnimBP_AnimGraphNode_TransitionResult_55CADA634E04C07CACFD52B557498337_Params
{
};

// Function ControlPanelPrinter_AnimBP.ControlPanelPrinter_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelPrinter_AnimBP_AnimGraphNode_TransitionResult_CE149DEC40D71055EC4E71AFE149526D
struct UControlPanelPrinter_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelPrinter_AnimBP_AnimGraphNode_TransitionResult_CE149DEC40D71055EC4E71AFE149526D_Params
{
};

// Function ControlPanelPrinter_AnimBP.ControlPanelPrinter_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelPrinter_AnimBP_AnimGraphNode_TransitionResult_C4DF0C884880C316C90446894FD8DC53
struct UControlPanelPrinter_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelPrinter_AnimBP_AnimGraphNode_TransitionResult_C4DF0C884880C316C90446894FD8DC53_Params
{
};

// Function ControlPanelPrinter_AnimBP.ControlPanelPrinter_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelPrinter_AnimBP_AnimGraphNode_TransitionResult_40B325D044380CB5B302E9BB6CA7FA2B
struct UControlPanelPrinter_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelPrinter_AnimBP_AnimGraphNode_TransitionResult_40B325D044380CB5B302E9BB6CA7FA2B_Params
{
};

// Function ControlPanelPrinter_AnimBP.ControlPanelPrinter_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelPrinter_AnimBP_AnimGraphNode_TransitionResult_E6C72BD24BA603C13E243DAC817F1F8B
struct UControlPanelPrinter_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelPrinter_AnimBP_AnimGraphNode_TransitionResult_E6C72BD24BA603C13E243DAC817F1F8B_Params
{
};

// Function ControlPanelPrinter_AnimBP.ControlPanelPrinter_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelPrinter_AnimBP_AnimGraphNode_TransitionResult_8830B79C4A538D8FCAB72E96E9BB957C
struct UControlPanelPrinter_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelPrinter_AnimBP_AnimGraphNode_TransitionResult_8830B79C4A538D8FCAB72E96E9BB957C_Params
{
};

// Function ControlPanelPrinter_AnimBP.ControlPanelPrinter_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelPrinter_AnimBP_AnimGraphNode_TransitionResult_58A0C10D43560918F3DF4B88F5AB42A8
struct UControlPanelPrinter_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelPrinter_AnimBP_AnimGraphNode_TransitionResult_58A0C10D43560918F3DF4B88F5AB42A8_Params
{
};

// Function ControlPanelPrinter_AnimBP.ControlPanelPrinter_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelPrinter_AnimBP_AnimGraphNode_TransitionResult_540BFE80454A9AE75F824FAFE3E9A996
struct UControlPanelPrinter_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelPrinter_AnimBP_AnimGraphNode_TransitionResult_540BFE80454A9AE75F824FAFE3E9A996_Params
{
};

// Function ControlPanelPrinter_AnimBP.ControlPanelPrinter_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelPrinter_AnimBP_AnimGraphNode_TransitionResult_7D4B717A488793B921AC58908634AE09
struct UControlPanelPrinter_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelPrinter_AnimBP_AnimGraphNode_TransitionResult_7D4B717A488793B921AC58908634AE09_Params
{
};

// Function ControlPanelPrinter_AnimBP.ControlPanelPrinter_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelPrinter_AnimBP_AnimGraphNode_TransitionResult_3A517C804CA321B13C3BB6B4C64AC072
struct UControlPanelPrinter_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelPrinter_AnimBP_AnimGraphNode_TransitionResult_3A517C804CA321B13C3BB6B4C64AC072_Params
{
};

// Function ControlPanelPrinter_AnimBP.ControlPanelPrinter_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelPrinter_AnimBP_AnimGraphNode_TransitionResult_9ECF81B141705884AD7FC5815DEDFF5E
struct UControlPanelPrinter_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelPrinter_AnimBP_AnimGraphNode_TransitionResult_9ECF81B141705884AD7FC5815DEDFF5E_Params
{
};

// Function ControlPanelPrinter_AnimBP.ControlPanelPrinter_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelPrinter_AnimBP_AnimGraphNode_TransitionResult_8E9BDAE949181EF9116E1C8FD26DE157
struct UControlPanelPrinter_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelPrinter_AnimBP_AnimGraphNode_TransitionResult_8E9BDAE949181EF9116E1C8FD26DE157_Params
{
};

// Function ControlPanelPrinter_AnimBP.ControlPanelPrinter_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelPrinter_AnimBP_AnimGraphNode_TransitionResult_623C2172450385E9A287A78417DA4B8A
struct UControlPanelPrinter_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelPrinter_AnimBP_AnimGraphNode_TransitionResult_623C2172450385E9A287A78417DA4B8A_Params
{
};

// Function ControlPanelPrinter_AnimBP.ControlPanelPrinter_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelPrinter_AnimBP_AnimGraphNode_TransitionResult_87AA352F490E16B858D67A9B0C0DD253
struct UControlPanelPrinter_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelPrinter_AnimBP_AnimGraphNode_TransitionResult_87AA352F490E16B858D67A9B0C0DD253_Params
{
};

// Function ControlPanelPrinter_AnimBP.ControlPanelPrinter_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelPrinter_AnimBP_AnimGraphNode_TransitionResult_4B0AB36C49EEE2D214172EADEFE27AB9
struct UControlPanelPrinter_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelPrinter_AnimBP_AnimGraphNode_TransitionResult_4B0AB36C49EEE2D214172EADEFE27AB9_Params
{
};

// Function ControlPanelPrinter_AnimBP.ControlPanelPrinter_AnimBP_C.BlueprintUpdateAnimation
struct UControlPanelPrinter_AnimBP_C_BlueprintUpdateAnimation_Params
{
	float                                              DeltaTimeX;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

// Function ControlPanelPrinter_AnimBP.ControlPanelPrinter_AnimBP_C.ExecuteUbergraph_ControlPanelPrinter_AnimBP
struct UControlPanelPrinter_AnimBP_C_ExecuteUbergraph_ControlPanelPrinter_AnimBP_Params
{
	int                                                EntryPoint;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
