#pragma once

#include "../SDK.h"

// Name: Astroneer-SDK, Version: 1.0.0

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

namespace SDK
{
//---------------------------------------------------------------------------
// Parameters
//---------------------------------------------------------------------------

// Function ControlPanelSpliltter_AnimBP.ControlPanelSpliltter_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelSpliltter_AnimBP_AnimGraphNode_TransitionResult_8B80306A4B6DF3230AF809B891DF0958
struct UControlPanelSpliltter_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelSpliltter_AnimBP_AnimGraphNode_TransitionResult_8B80306A4B6DF3230AF809B891DF0958_Params
{
};

// Function ControlPanelSpliltter_AnimBP.ControlPanelSpliltter_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelSpliltter_AnimBP_AnimGraphNode_ModifyBone_DA3BB88B4F447B2F5702A5B2AFAC09FB
struct UControlPanelSpliltter_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelSpliltter_AnimBP_AnimGraphNode_ModifyBone_DA3BB88B4F447B2F5702A5B2AFAC09FB_Params
{
};

// Function ControlPanelSpliltter_AnimBP.ControlPanelSpliltter_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelSpliltter_AnimBP_AnimGraphNode_ModifyBone_3D46C7CE402C0AA225BD829C9D069D5D
struct UControlPanelSpliltter_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelSpliltter_AnimBP_AnimGraphNode_ModifyBone_3D46C7CE402C0AA225BD829C9D069D5D_Params
{
};

// Function ControlPanelSpliltter_AnimBP.ControlPanelSpliltter_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelSpliltter_AnimBP_AnimGraphNode_ModifyBone_CC78B9A945009BEA044DE689E8E14B16
struct UControlPanelSpliltter_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelSpliltter_AnimBP_AnimGraphNode_ModifyBone_CC78B9A945009BEA044DE689E8E14B16_Params
{
};

// Function ControlPanelSpliltter_AnimBP.ControlPanelSpliltter_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelSpliltter_AnimBP_AnimGraphNode_TransitionResult_893766014AD126EF34B1638638EBA5F0_1
struct UControlPanelSpliltter_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelSpliltter_AnimBP_AnimGraphNode_TransitionResult_893766014AD126EF34B1638638EBA5F0_1_Params
{
};

// Function ControlPanelSpliltter_AnimBP.ControlPanelSpliltter_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelSpliltter_AnimBP_AnimGraphNode_TransitionResult_5969C1C64C2E173B85EFEEA288061118_1
struct UControlPanelSpliltter_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelSpliltter_AnimBP_AnimGraphNode_TransitionResult_5969C1C64C2E173B85EFEEA288061118_1_Params
{
};

// Function ControlPanelSpliltter_AnimBP.ControlPanelSpliltter_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelSpliltter_AnimBP_AnimGraphNode_TransitionResult_7A10360345FFED85B515DE9758451B20
struct UControlPanelSpliltter_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelSpliltter_AnimBP_AnimGraphNode_TransitionResult_7A10360345FFED85B515DE9758451B20_Params
{
};

// Function ControlPanelSpliltter_AnimBP.ControlPanelSpliltter_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelSpliltter_AnimBP_AnimGraphNode_TransitionResult_893766014AD126EF34B1638638EBA5F0
struct UControlPanelSpliltter_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelSpliltter_AnimBP_AnimGraphNode_TransitionResult_893766014AD126EF34B1638638EBA5F0_Params
{
};

// Function ControlPanelSpliltter_AnimBP.ControlPanelSpliltter_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelSpliltter_AnimBP_AnimGraphNode_TransitionResult_5969C1C64C2E173B85EFEEA288061118
struct UControlPanelSpliltter_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelSpliltter_AnimBP_AnimGraphNode_TransitionResult_5969C1C64C2E173B85EFEEA288061118_Params
{
};

// Function ControlPanelSpliltter_AnimBP.ControlPanelSpliltter_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelSpliltter_AnimBP_AnimGraphNode_TransitionResult_8B80306A4B6DF3230AF809B891DF0958_1
struct UControlPanelSpliltter_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelSpliltter_AnimBP_AnimGraphNode_TransitionResult_8B80306A4B6DF3230AF809B891DF0958_1_Params
{
};

// Function ControlPanelSpliltter_AnimBP.ControlPanelSpliltter_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelSpliltter_AnimBP_AnimGraphNode_TransitionResult_4FEC2FCB488087EB0C5ED0815773EE7D
struct UControlPanelSpliltter_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelSpliltter_AnimBP_AnimGraphNode_TransitionResult_4FEC2FCB488087EB0C5ED0815773EE7D_Params
{
};

// Function ControlPanelSpliltter_AnimBP.ControlPanelSpliltter_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelSpliltter_AnimBP_AnimGraphNode_TransitionResult_B254970048C3D7972F537AAA389DDD8D
struct UControlPanelSpliltter_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelSpliltter_AnimBP_AnimGraphNode_TransitionResult_B254970048C3D7972F537AAA389DDD8D_Params
{
};

// Function ControlPanelSpliltter_AnimBP.ControlPanelSpliltter_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelSpliltter_AnimBP_AnimGraphNode_TransitionResult_7A10360345FFED85B515DE9758451B20_1
struct UControlPanelSpliltter_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelSpliltter_AnimBP_AnimGraphNode_TransitionResult_7A10360345FFED85B515DE9758451B20_1_Params
{
};

// Function ControlPanelSpliltter_AnimBP.ControlPanelSpliltter_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelSpliltter_AnimBP_AnimGraphNode_TransitionResult_8B80306A4B6DF3230AF809B891DF0958_2
struct UControlPanelSpliltter_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelSpliltter_AnimBP_AnimGraphNode_TransitionResult_8B80306A4B6DF3230AF809B891DF0958_2_Params
{
};

// Function ControlPanelSpliltter_AnimBP.ControlPanelSpliltter_AnimBP_C.EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelSpliltter_AnimBP_AnimGraphNode_TransitionResult_7A10360345FFED85B515DE9758451B20_2
struct UControlPanelSpliltter_AnimBP_C_EvaluateGraphExposedInputs_ExecuteUbergraph_ControlPanelSpliltter_AnimBP_AnimGraphNode_TransitionResult_7A10360345FFED85B515DE9758451B20_2_Params
{
};

// Function ControlPanelSpliltter_AnimBP.ControlPanelSpliltter_AnimBP_C.BlueprintUpdateAnimation
struct UControlPanelSpliltter_AnimBP_C_BlueprintUpdateAnimation_Params
{
	float                                              DeltaTimeX;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

// Function ControlPanelSpliltter_AnimBP.ControlPanelSpliltter_AnimBP_C.ExecuteUbergraph_ControlPanelSpliltter_AnimBP
struct UControlPanelSpliltter_AnimBP_C_ExecuteUbergraph_ControlPanelSpliltter_AnimBP_Params
{
	int                                                EntryPoint;                                               // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
